blood/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls",namespace='home')),
    path('information/',include("info.urls",namespace='info')),
    path('points/',include("points.urls",namespace='points')),
    path('register/',include("register.urls",namespace='register')),
    path('needblood/',include("needblood.urls",namespace='needblood')),
    # path('register/',include("register.urls",namespace='register')),
    # path('needblood/',include("needblood.urls",namespace='needblood')),
]

home/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


app_name="home"

urlpatterns = [

  url(r"^$", views.IndexView.as_view(), name="index"),

]

info/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


app_name="info"

urlpatterns = [

  url(r"^$", views.InfoView.as_view(), name="info"),

]

needblood/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


app_name="needblood"

urlpatterns = [

  url(r"^$", views.NeedBloodView, name="needblood"),

]

points/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name="points"

urlpatterns = [

  url(r"^$", views.PointView.as_view(), name="points"),

]

register/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views


app_name="register"

urlpatterns = [

  url(r"^$", views.Register, name="register"),

]

home/models.py
from django.db import models

# Create your models here.

info/models.py
from django.db import models

# Create your models here.

needblood/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import Permission, User


BLOOD_GROUPS=(
('A+','A+'),
('A-','A-'),
('B+','B+'),
('B-','B-'),
('O+','O+'),
('O-','O-'),
('AB+','AB+'),
('AB-','AB-'),
)
class Receiver(models.Model):
    receiver= models.CharField(max_length = 250)
    blood_group = models.CharField(max_length=50, choices=BLOOD_GROUPS, default='black')
    mobile_no = models.CharField(max_length = 12)
    email = models.CharField(max_length = 250)
    hospital = models.CharField(max_length = 250)
    city = models.CharField(max_length = 20)

    def __str__(self):
        return str(self.receiver)

points/models.py
from django.db import models

# Create your models here.

register/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import Permission, User


BLOOD_GROUPS=(
('A+','A+'),
('A-','A-'),
('B+','B+'),
('B-','B-'),
('O+','O+'),
('O-','O-'),
('AB+','AB+'),
('AB-','AB-'),
)
class Doner(models.Model):
    doner= models.CharField(max_length = 250)
    blood_group = models.CharField(max_length=50, choices=BLOOD_GROUPS, default='black')
    mobile_no = models.CharField(max_length = 12)
    email = models.CharField(max_length = 250)
    city = models.CharField(max_length = 20)

    def __str__(self):
        return str(self.doner)

needblood/forms.py
from django import forms
from .models import Receiver


class ReceiverForm(forms.ModelForm):


    class Meta:
        model = Receiver
        fields = ['receiver', 'blood_group', 'mobile_no', 'email','hospital','city']

register/forms.py
from django import forms
from .models import Doner


class RegisterForm(forms.ModelForm):


    class Meta:
        model = Doner
        fields = ['doner', 'blood_group', 'mobile_no', 'email','city']

home/views.py
from django.urls import reverse,reverse_lazy
from django.http import HttpResponseRedirect
# from django.contrib.auth import login, logout
from django.views.generic import CreateView, TemplateView
# from . import forms

class IndexView(TemplateView):
    template_name = 'home/index.html'

info/views.py
from django.urls import reverse,reverse_lazy
from django.http import HttpResponseRedirect
# from django.contrib.auth import login, logout
from django.views.generic import CreateView, TemplateView
# from . import forms

class InfoView(TemplateView):
    template_name = 'info.html'

needblood/views.py
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import Receiver
from .forms import ReceiverForm
from register.models import Doner
import requests

url = "https://www.fast2sms.com/dev/bulk"

def NeedBloodView(request):
    form = ReceiverForm(request.POST or None)
    if form.is_valid():
        receiver= form.save(commit=False)
        user= form.cleaned_data.get('receiver')
        receiver.receiver=user
        blood_group=form.cleaned_data.get('blood_group')
        print(blood_group)
        receiver.blood_group = blood_group
        mobile_no=form.cleaned_data.get('mobile_no')
        receiver.mobile_no = mobile_no
        receiver.email = form.cleaned_data.get('email')
        hospital=form.cleaned_data.get('hospital')
        receiver.hospital = hospital
        receiver_city=form.cleaned_data.get('city')
        receiver.city = receiver_city

        receiver.save()
        numbers=[]
        for doner in Doner.objects.filter(city__startswith=receiver_city):
            numbers.append(doner.mobile_no)

        msg= user +" Need "+ blood_group  + "Blood At "+ hospital+","+ receiver_city +" Call on "+mobile_no+" from Helping Hand."
        for number in numbers:

            payload = "sender_id=FSTSMS&message="+msg+"&language=english&route=p&numbers="+number
            headers = {
            'authorization': "Xn4BP6YkCtab0iTuSgH8WEzJONveKUpIhwARlDx3MZroqFcmVQcD8kBNCzfen2FPpIlsHtZKmJ47X9gi",
            'Content-Type': "application/x-www-form-urlencoded",
            'Cache-Control': "no-cache",
            }
            response = requests.request("POST", url, data=payload, headers=headers)

        return render(request, 'thanks1.html', {'receiver': receiver,'user':user})
    context = {
            "form": form,
        }
    return render(request, 'need.html', context)

points/views.py
from django.urls import reverse,reverse_lazy
from django.http import HttpResponseRedirect
# from django.contrib.auth import login, logout
from django.views.generic import CreateView, TemplateView
# from . import forms

class PointView(TemplateView):
    template_name = 'point.html'

register/views.py
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import Doner
from .forms import RegisterForm

def Register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        doner= form.save(commit=False)
        user= form.cleaned_data.get('doner')
        doner.doner=user
        doner.blood_group = form.cleaned_data.get('blood_group')
        doner.mobile_no = form.cleaned_data.get('mobile_no')
        doner.email = form.cleaned_data.get('email')
        doner.city = form.cleaned_data.get('city')

        doner.save()
        return render(request, 'thanks0.html', {'doner': doner,'user':user})
    context = {
            "form": form,
        }
    return render(request, 'register.html', context)

home/templates/home/index.html
{% extends 'base.html' %}
{% block login_active %}active{% endblock %}

{% block body %}

            <div class="row">
                <div class="col-sm-6">
                    <p class="text">
                        <center> <font color="#6d6d46" size="5px"><u> About us </u></font> </center><br>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>

                <div class="col-sm-6">
                    <p class="text">
                        <center> <font color="#6d6d46" size="5px"><u>Importance of Blood Donation! </u></font> </center><br>
                        <ul>
                            <li>A single session of blood donation can benefit as many as 4 sets of people, when divided into its various components (red blood cells, plasma, platelets and cryoprecipitate)</li>
                            <li>A premature baby can be given a second chance with as little as 3 teaspoons of your blood.</li>
                            <li>Someone in this world is in need of blood, every 2-5 seconds.</li>
                            <li>American citizen, James Harris, saved 2 million babies through multiple donationsof his rare blood type.</li>
                            <li>IrritaThere is no substitute for human blood. Therefore, all medical care depends on blood donation ability</li>

                        </ul>
                    </p>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-xs-12">
                    <p class="lead">
                        <center>
                            <a href="{% url 'register:register' %}" class="btn btn-md btn-default" >Register as a Donor</a>
                            <a href="{% url 'needblood:needblood' %}" class="btn btn-md btn-default">Request Blood</a>
                        </center>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="inner">
                        <p><h4>Project by <b>Team .onion</b></h4></p>
                    </div>
                </div>
            </div>


        {% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/static/home/images/logo002.png">
        <title>Helping Hand</title>
        <link href="/static/home/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/home/css//ie10-viewport-bug-workaround.css" rel="stylesheet">
        <link href="/static/home/css/cover.css" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
        <script src="/static/home/js/ie-emulation-modes-warning.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Concert+One|Lobster" rel="stylesheet">

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <!-- <meta name="keywords" content="Curved Contact Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs Sign up Web Templates,
        Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free web designs for Nokia, Samsung, LG, SonyEricsson, Motorola web design"> -->
        <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <!-- Custom Theme files -->
        <link href="/static/home/css/style_contactus.css" rel='stylesheet' type='text/css' />
        <!-- <link href="/static/home/css/bootstrap.css" rel='stylesheet' type='text/css' /> -->
        <!--fonts-->
        <link href="//fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700,800" rel="stylesheet">
        <!--//fonts-->

    </head>
    <body>
        <div class="container-fluid">
            <div class="row hbgcolor">
                <div id="logo" class="col-sm-2 col-md-2 col-xs-2"><img src="/static/home/images/logo003.png" height="125px" width="125px" margin-left="auto" margin-right="auto"></div>
                <div id="head" class="col-sm-6 col-md-6 col-xs-6 main_title">
                    <p class="header_blood">
                        HELPING HAND
                        <p style="font-family: 'Lobster', cursive; font-size: 30px;"> An SMS is saving lives by arranging blood in time!!</p>
                    </p>
                </div>
                <div id="twitter"class="col-sm-2 col-md-2 col-xs-2">
                    <font size="100px"><a href="https://twitter.com/hashtag/bloodinthecity?src=hash"><i class="fab fa-twitter" size="7x"></i></a></font>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-md-12 col-xs-12">
                    <nav>
                        <ul class="nav masthead-nav">
                            <li class="active"><a href="{% url 'home:index' %}">Home</a></li>
                            <li><a href="{% url 'info:info' %}"><font color="#ffffff">Information</font></a></li>
                            <li><a href="{% url 'points:points' %}"><font color="#ffffff">Point to Remember</font></a></li>
                        </ul>
                    </nav>
                </div>
            </div>

            {% block body %}
            {% endblock %}



                <!-- Bootstrap core JavaScript
                ================================================== -->
                <!-- Placed at the end of the document so the pages load faster -->
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
                <script>window.jQuery || document.write('<script src="/static/home/js/jquery.min.js"><\/script>')</script>
                <script src="/static/home/js/bootstrap.min.js"></script>
                <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
                <script src="/static/home/js/ie10-viewport-bug-workaround.js"></script>
              </body>
            </html>

templates/info.html
{% extends 'base.html' %}
{% block login_active %}active{% endblock %}

{% block body %}
        <br>
        <center>
            <table class="tg">
                <tr>
                    <th class="td_row">Blood Group</th>
                    <th class="td_row">A+</th>
                    <th class="td_row">B+</th>
                    <th class="td_row">O+</td>
                    <th class="td_row">AB+</td>
                    <th class="td_row">A-</td>
                    <th class="td_row">B-</td>
                    <th class="td_row">O-</td>
                    <th class="td_row">AB-</td>

                </tr>
                <tr>
                    <td class="td_row">A+</i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                </tr>
                <tr>
                    <td class="td_row">A-</td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>

                </tr>
                <tr>
                    <td class="td_row">B+</td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>

                </tr>
                <tr>
                    <td class="td_row">B-</td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>

                </tr>
                <tr>
                    <td class="td_row">O+</td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                </tr>
                <tr>
                    <td class="td_row">O-</td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                </tr>
                <tr>
                    <td class="td_row">AB+</td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                </tr>
                <tr>
                    <td class="td_row">AB-</td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-times"></i></td>
                    <td class="td_data"><i class="fa fa-check"></i></td>
                </tr>
            </table>
        </center>
        <br>

{% endblock %}

templates/need.html
{% extends 'base.html' %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="login-w3l">
<div class="top-img-agileits-w3layouts">
<h2 class="sub-head-w3-agileits">Request</h2>
<p>Fillout the form below</p>
<div class="login-form">
<form method="post">
{% csrf_token %}
{{form.as_p }}
<br>
<input class="form-check-input" type="checkbox" value="" id="invalidCheck2" required>
<label class="form-check-label" for="invalidCheck2">
<p id="color">I've given correct data!</p>
<br>
<input type="submit" value="Submit">
</form>
</div>
</div>
</div>

  <!-- form ends -->
  <style>
  #color{
  color: white;
  }
  </style>

  {% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block login_active %}active{% endblock %}

{% block body %}
	        <div class="login-w3l">
			<div class="top-img-agileits-w3layouts">
				<h2 class="sub-head-w3-agileits">Register</h2>
				<p>Fillout the form below</p>
				<div class="login-form">
				<form method="post">
					{% csrf_token %}
					{{form.as_p }}
          <br>
          <input class="form-check-input" type="checkbox" value="" id="invalidCheck2" required>
          <label class="form-check-label" for="invalidCheck2">
              <a href="{% url 'points:points' %}" target="_blank"> Read "Points to Remember" </a>
          </label>
          <br>
					<input type="submit" value="Register">
				</form>
			</div>
			</div>
				</div>
                <style>
                a{
                color: white;
                }
                </style>
{% endblock %}

templates/thanks0.html
{% extends 'base.html' %}
{% block body %}

<div id="box">

<h1 id="thanks">Thanks for Registering as A Doner {{user}}! You will receive An SMS if someone needs Blood in Your City!</h1>

</div>


<style>
#box{
position:absolute;
top:50%;
left:50%;
transform:translate(-50%,-50%);
-ms-transform:translate(-50%,-50%)


}
#thanks{
  text-align: center;
  color:white;
}

</style>


{% endblock %}

templates/thanks1.html
{% extends 'base.html' %}
{% block body %}

<div id="box">

<h1 id="thanks">Thanks for Requesting Blood {{user}}! We Will Try Our Best To Get the Required Blood On Time.</h1>

</div>


<style>
#box{
position:absolute;
top:50%;
left:50%;
transform:translate(-50%,-50%);
-ms-transform:translate(-50%,-50%)


}
#thanks{
  text-align: center;
  color:white;
}

</style>


{% endblock %}